#!/command/with-contenv bash
# shellcheck shell=bash
# ==============================================================================
# Home Assistant Add-on: CouchDB for Obsidian LiveSync
# Takes down the S6 supervisor when CouchDB fails
# ==============================================================================

declare exit_code=${1}

if [[ "${exit_code}" -ne 0 ]] && [[ "${exit_code}" -ne 256 ]]; then
    echo "CouchDB failed with exit code ${exit_code}"
    echo "Halting add-on..."
    /run/s6/basedir/bin/halt
fi
